### ISSUE TITLE
Ciphersuite naming convension

### ISSUE THREAD

**Issue by dajiaji** [cose-wg/HPKE#30]
A naming convention for cipher suites needs to be decided.

I think the following proposal, which was established during discussions with Hannes, is relatively reasonable.

ex) HPKE-v1-Base-P256-SHA256-AES128GCM ... (A)

Additionally, there are two other proposals: one, which is suggested by Ilari, involves utilizing the HPKE IANA registered values as follows:

ex) HPKE-v1-Base-16-1-1 ... (B)

and the other is accurately representing everything:

ex) HPKE-v1-Base-DHKEM-P256-HKDF-SHA256-SHA256-AES128 ... (C)

**Comment by selfissued** [comment]
Agree that we need a naming convention.  For COSE, the names can be long and descriptive if we like, since they all eventually just map to small numeric `alg` values.

But I suggest that we also be thinking about what JOSE `alg` values we want, since it's likely that that work will happen in parallel.  We should try for reasonable brevity for those name, if possible.  And ideally, COSE and JOSE will use the same names.

**Comment by ilaril** [comment]
I think the full names are just too gnarly, even for the COSE registry.

And I would not put much weight on JOSE here, because HPKE and JWE do not seem to mix (unlike HPKE and COSE_Encrypt).

**Comment by dajiaji** [comment]
> But I suggest that we also be thinking about what JOSE alg values we want, since it's likely that that work will happen in parallel. We should try for reasonable brevity for those name, if possible. And ideally, COSE and JOSE will use the same names.

I agree with you. I also think it is necessary to give names that can be used as it is in JOSE.
